Manas week 2
pgRouting/GSoC-pgRouting pull request #219
Opened 2022-06-21 11:10 UTC by Manas23601

Created an empty file for knapsack_0_1

2022-06-21 12:52 UTC, Manas23601 commented
How do I stop Github actions from running build each and every time I push some changes

2022-06-21 14:50 UTC, Manas23601 commented
I think I have created a basic skeleton(still incomplete) for now.  If there are problems, please let me know. Please direct me to any resources if necessary

2022-06-22 08:22 UTC, krashish8 commented
> How do I stop Github actions from running build each and every time I push some changes?

I don't think you should do that. It's good to see the Actions result after every push. Initially, they are going to fail.
Anyway, if you want, you can temporarily disable the corresponding actions in the Actions tab **for your fork**, or can comment the corresponding workflow file.

2022-06-22 08:29 UTC, krashish8 commented
@Manas23601 Maybe it's a good idea to reconsider the naming of the functions or the directory structure.
You can probably ask in the pgRouting Gitter channel for the same.

I think you should only use underscores in the function name, not dashes. Some function names suggestions:
- vrp_or_knapsack_0_1
- vrp_or_knapsack
- vrp_knapsack_0_1 (OR stands for Operations Research tools, but it may mislead the users sometimes)
- vrp_knapsack
- vrp_knapsack_01

The directory could be `knapsack` only, or `or_tools` or something related, but not `knapsack_0-1`.

2022-06-23 15:21 UTC, cvvergara requested changes

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/_knapsack_0-1.sql
> +CREATE OR REPLACE FUNCTION _vrp_or_knapsack_0-1(
postgres names can not have dashes.

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/_knapsack_0-1.sql
> +Copyright (c) 2021 Celia Virginia Vergara Castillo
I am not developing this function.
Remove my name

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/knapsack_0-1.sql
> +CREATE OR REPLACE FUNCTION _vrp_or_knapsack_0-1(
Postgres names can not have dashes.
(I really dont know of a language that can have dashes on the names, as a dash is the minus sign)

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/knapsack_0-1.sql
> +Copyright (c) 2021 Celia Virginia Vergara Castillo
Remove my name

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/_knapsack_0-1.sql
> +Copyright (c) 2021 Joseph Emile Honour Percival
I don't think Iosefa is developing this function.
Remove his name

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/_knapsack_0-1.sql
> +
I do not see you name as the function developer.
Ar you going to give Iosefa and me the credit for your work?

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/knapsack_0-1.sql
> +
I do not see you name as the function developer.
Ar you going to give Iosefa and me the credit for your work?

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/knapsack_0-1.sql
> +Copyright (c) 2021 Joseph Emile Honour Percival
Remove Iosefa's name

2022-06-23 15:21 UTC, cvvergara commented on sql/knapsack_0-1/knapsack_0-1.sql
> +COMMENT ON FUNCTION __vrp_or_knapsack_0-1(TEXT, TEXT, INTEGER)
I am no compiler, but the first underscore looks way too long.

2022-06-23 15:24 UTC, cvvergara commented
I am wondering, is there a knapsack that is not 0-1?
For the moment in vrpRouting the answer is NO.
`vrp_knapsack` I prefer as the name, and if in there future there is another kind of knapsack we will figure out the name

2022-06-23 15:44 UTC, Manas23601 commented
I will immediately look at the name changes. I think I forgot to commit those changes

2022-06-26 17:30 UTC, merged